In [2]:
#import statements
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline

In [3]:
#Load dataset
kickstarter_data = pd.read_csv("Kickstarter_preprocessed.csv")

In [4]:
#Check what the dataset looks like
kickstarter_data.head(5)

Unnamed: 0                                                url  \
0           1  https://www.kickstarter.com/projects/100143389...   
1           2  https://www.kickstarter.com/projects/100146151...   
2           3  https://www.kickstarter.com/projects/100217190...   
3           4  https://www.kickstarter.com/projects/100296962...   
4           5  https://www.kickstarter.com/projects/100345889...   

                                          urlProfile  \
0  https://www.kickstarter.com/profile/1001433890...   
1  https://www.kickstarter.com/profile/100146151/...   
2  https://www.kickstarter.com/profile/1002171905...   
3  https://www.kickstarter.com/profile/1002969621...   
4  https://www.kickstarter.com/profile/1003458897...   

                                       campaignTitle        category  \
0                                         Die Kamera       Webseries   
1                          "Flores" Documentary Film     Documentary   
2  F(r)iction #7 - A Fine Art & Literature Collec...         Fiction   
3                                      Design Canada  Graphic Design   
4  New HyperKid Book - The Cyborg at the End of t...     Young Adult   

                       creator      goal             location  \
0               Georg Melichar  58367.10      Vienna, Austria   
1            Francisco Viveros   6994.52  Mexico City, Mexico   
2          Tethered by Letters   3000.00           Denver, CO   
3              Jessica Edwards  80000.00    Vancouver, Canada   
4  Richard Daub & Emerson Daub  10000.00     White Plains, NY   

   totalNumberBackers  numComments      ...                    endDate  \
0                   1            0      ...        2017-03-31 14:30:00   
1                  51            1      ...        2017-04-20 00:32:00   
2                 119            5      ...        2017-04-22 14:45:00   
3                1483           34      ...        2017-03-30 22:00:00   
4                   0            0      ...        2017-04-25 11:41:00   

             startDate  estimatedDelivery   experience  canceled  \
0  2017-03-01 15:30:00         229.177083     1.141667     False   
1  2017-02-19 01:32:00         254.523232    73.341667     False   
2  2017-03-23 14:45:00          16.135417   683.740278     False   
3  2017-02-28 13:09:00         149.690476  2265.436806     False   
4  2017-03-26 11:41:00           5.513194     9.996528      True   

  averageBackersRequired  aggregatedPerkValue overPaying shippingWorld  \
0             734.177358                  0.0       1.06           1.0   
1             179.346667                802.0    7133.82           1.0   
2              75.000000               3473.0     951.00           1.0   
3             290.909091              86240.0   12938.00           1.0   
4             571.428571                  0.0       0.00           0.5   

  numCompetitors  
0             26  
1             88  
2             64  
3             23  
4             13  

[5 rows x 54 columns]

In [6]:
#list of columns
columns = kickstarter_data.columns.tolist() #column list
columns

['Unnamed: 0',
 'url',
 'urlProfile',
 'campaignTitle',
 'category',
 'creator',
 'goal',
 'location',
 'totalNumberBackers',
 'numComments',
 'numUpdates',
 'totalPledge',
 'backed',
 'comments',
 'created',
 'joinKS',
 'facebookFriends',
 'urlCreator',
 'websites',
 'mainCategory',
 'countryState',
 'city',
 'projectsWeLove',
 'continent',
 'valuta',
 'success',
 'percentageGoal',
 'lowestPerk',
 'highestPerk',
 'medianPerk',
 'lowestPerkPriceOriginal',
 'numPerks',
 'numCollaborators',
 'noFacebookFriends',
 'numSuccessfulCampaigns',
 'numLiveCampaigns',
 'pastSuccessRate',
 'totWordCount',
 'mainVideo',
 'numAdditionalVideos',
 'numImages',
 'viewGallery',
 'addedPerks',
 'duration',
 'endDate',
 'startDate',
 'estimatedDelivery',
 'experience',
 'canceled',
 'averageBackersRequired',
 'aggregatedPerkValue',
 'overPaying',
 'shippingWorld',
 'numCompetitors']

In [7]:
#Check what some data look like
print(kickstarter_data.loc[0,"url"])
print(kickstarter_data.loc[0, "urlProfile"])
print(kickstarter_data.loc[0, "websites"])
print(kickstarter_data.loc[5, "mainVideo"])#yes video: 1 #no video: 0
print(kickstarter_data.loc[0, "success"])
print(kickstarter_data.loc[50, "pastSuccessRate"])
print(kickstarter_data.loc[50, "comments"])
print(kickstarter_data.loc[50, "numComments"])
print(kickstarter_data.loc[50, "urlCreator"])
print(kickstarter_data.loc[50, "mainCategory"])
print(kickstarter_data.loc[50, "category"])
print(kickstarter_data.loc[50, "projectsWeLove"])
print(kickstarter_data.loc[30, "lowestPerk"])
print(kickstarter_data.loc[30, "lowestPerkPriceOriginal"])

https://www.kickstarter.com/projects/1001433890/die-kamera?ref=ending_soon
https://www.kickstarter.com/profile/1001433890/created
http://www.digitalmovies.at/
0
0
0.5
2
3
https://www.kickstarter.com/projects/1032066976/nowhere-michigan-in-post-production-now/creator_bio
Film & Video
Thrillers
False
1.0
1


In [36]:
#Filter out unnecessary columns -at launch point
no_need = ["Unnamed: 0","url", "urlProfile", "url", "campaignTitle", "aggregatedPerkValue","creator", "location","totalNumberBackers", "numComments","numUpdates","totalPledge","backed","comments","created","joinKS","urlCreator","websites","countryState","city","projectsWeLove","continent","valuta","lowestPerkPriceOriginal","noFacebookFriends","pastSuccessRate","numAdditionalVideos","viewGallery","addedPerks","endDate","startDate","experience","percentageGoal","numLiveCampaigns","averageBackersRequired","canceled","highestPerk","lowestPerk","overPaying","shippingWorld","numCompetitors"]
kickstarter = kickstarter_data.copy() #kickstarter_data remains the same
kickstarter.drop(no_need, axis=1, inplace=True)
kickstarter.head(10)

category      goal  facebookFriends  mainCategory  success  \
0       Webseries  58367.10            737.0  Film & Video        0   
1     Documentary   6994.52           2480.0  Film & Video        1   
2         Fiction   3000.00            461.0    Publishing        1   
3  Graphic Design  80000.00            574.5        Design        1   
4     Young Adult  10000.00            574.5    Publishing        0   
5     Digital Art    385.91            574.5           Art        0   
6     Documentary   3500.00            702.0  Film & Video        1   
7            Food  10000.00           4981.0          Food        0   
8             Art   2253.30            270.0           Art        1   
9       Sculpture  81289.00           5000.0           Art        0   

   medianPerk  numPerks  numCollaborators  numSuccessfulCampaigns  \
0        79.5         4                 0                       0   
1        39.0        11                 0                       1   
2        40.0        20                 0                       4   
3       275.0        28                 0                       2   
4        17.5         6                 0                       0   
5        13.5         8                 0                       0   
6       300.0         9                 0                       1   
7       100.0         1                 0                       0   
8        26.0         3                 0                       1   
9       125.0         6                 0                       0   

   totWordCount  mainVideo  numImages   duration  estimatedDelivery  
0           253          1          0  29.958333         229.177083  
1          1165          1          7  59.958333         254.523232  
2          1371          1         12  30.000000          16.135417  
3          1040          1         34  30.368715         149.690476  
4          1641          1          0  30.000000           5.513194  
5           158          0          4  31.000000          15.492361  
6           897          1          0  21.628322         135.277778  
7           197          1          0  59.958333         -20.712500  
8           305          1          0  12.559942          -1.666667  
9           289          0          0  30.000000         226.521528

In [37]:
#Check kick_copy's columns
kickstarter.columns

Index(['category', 'goal', 'facebookFriends', 'mainCategory', 'success',
       'medianPerk', 'numPerks', 'numCollaborators', 'numSuccessfulCampaigns',
       'totWordCount', 'mainVideo', 'numImages', 'duration',
       'estimatedDelivery'],
      dtype='object')

In [39]:
#Change the order of kick_copy's columns
kickstarter = kickstarter[["mainCategory","category","goal","duration","numPerks","medianPerk","estimatedDelivery","mainVideo","numSuccessfulCampaigns","facebookFriends","numCollaborators","totWordCount","numImages", "success"]]
kickstarter.head(5)

mainCategory        category      goal   duration  numPerks  medianPerk  \
0  Film & Video       Webseries  58367.10  29.958333         4        79.5   
1  Film & Video     Documentary   6994.52  59.958333        11        39.0   
2    Publishing         Fiction   3000.00  30.000000        20        40.0   
3        Design  Graphic Design  80000.00  30.368715        28       275.0   
4    Publishing     Young Adult  10000.00  30.000000         6        17.5   

   estimatedDelivery  mainVideo  numSuccessfulCampaigns  facebookFriends  \
0         229.177083          1                       0            737.0   
1         254.523232          1                       1           2480.0   
2          16.135417          1                       4            461.0   
3         149.690476          1                       2            574.5   
4           5.513194          1                       0            574.5   

   numCollaborators  totWordCount  numImages  success  
0                 0           253          0        0  
1                 0          1165          7        1  
2                 0          1371         12        1  
3                 0          1040         34        1  
4                 0          1641          0        0

In [40]:
#Categorize by mainCategory
#show main category list
kickstarter["mainCategory"].unique()

array(['Film & Video', 'Publishing', 'Design', 'Art', 'Food', 'Fashion',
       'Games', 'Theater', 'Music', 'Crafts', 'Technology', 'Comics',
       'Photography', 'Journalism', 'Dance'], dtype=object)

In [41]:
kc_film_video = kickstarter[kickstarter["mainCategory"]=="Film & Video"].copy()
kc_publishing = kickstarter[kickstarter["mainCategory"]=="Publishing"].copy()
kc_design = kickstarter[kickstarter["mainCategory"]=="Design"].copy()
kc_art = kickstarter[kickstarter["mainCategory"]=="Art"].copy()
kc_food = kickstarter[kickstarter["mainCategory"]=="Food"].copy()
kc_fashion = kickstarter[kickstarter["mainCategory"]=="Fashion"].copy()
kc_games = kickstarter[kickstarter["mainCategory"]=="Games"].copy()
kc_theater = kickstarter[kickstarter["mainCategory"]=="Theater"].copy()
kc_music = kickstarter[kickstarter["mainCategory"]=="Music"].copy()
kc_crafts = kickstarter[kickstarter["mainCategory"]=="Crafts"].copy()
kc_technology = kickstarter[kickstarter["mainCategory"]=="Technology"].copy()
kc_comics = kickstarter[kickstarter["mainCategory"]=="Comics"].copy()

In [42]:
kc_dfs = [kc_film_video, kc_publishing, kc_design, kc_art, kc_food, kc_fashion, kc_games, kc_theater, kc_music, kc_crafts, kc_technology, kc_comics]
#for each main Category, show a list of subcategories
for df in kc_dfs:
    print(df["category"].max())
#For example, in this case, kc_film_video (kc_dfs[0]) has 20 different subcategories!

Webseries
Zines
Product Design
Video Art
Vegan
Ready-to-wear
Video Games
Theater
World Music
Woodworking
Web
Webcomics


In [43]:
#for each dataframe, convert categorical data to numerical
kc_dfs = [kc_film_video, kc_publishing, kc_design, kc_art, kc_food, kc_fashion, kc_games, kc_theater, kc_music, kc_crafts, kc_technology, kc_comics]
for df in kc_dfs:
    df["category"] = pd.Categorical(df["category"]).codes
kc_film_video.head()

mainCategory  category      goal   duration  numPerks  medianPerk  \
0   Film & Video        20  58367.10  29.958333         4        79.5   
1   Film & Video         3   6994.52  59.958333        11        39.0   
6   Film & Video         3   3500.00  21.628322         9       300.0   
21  Film & Video         1   3497.26  29.958333        14        52.0   
23  Film & Video         3  80000.00  30.000000        18       165.0   

    estimatedDelivery  mainVideo  numSuccessfulCampaigns  facebookFriends  \
0          229.177083          1                       0            737.0   
1          254.523232          1                       1           2480.0   
6          135.277778          1                       1            702.0   
21          26.611409          0                       1            751.0   
23         106.156944          1                       0            945.0   

    numCollaborators  totWordCount  numImages  success  
0                  0           253          0        0  
1                  0          1165          7        1  
6                  0           897          0        1  
21                 1          2116         32        1  
23                 0          2580         47        0

In [16]:
kc_dfs = [kc_film_video, kc_publishing, kc_design, kc_art, kc_food, kc_fashion, kc_games, kc_theater, kc_music, kc_crafts, kc_technology, kc_comics]
#for each main Category, show a list of subcategories
for df in kc_dfs:
    print(df["category"].max())
#For example, in this case, kc_film_video (kc_dfs[0]) has 20 different subcategories!

20
17
6
13
12
9
8
7
18
11
16
5


In [46]:
#Import scikit
from sklearn.model_selection import train_test_split #To split our data into train & test
from sklearn.ensemble import RandomForestClassifier #To train our model
from sklearn.metrics import classification_report, confusion_matrix #To see how accurate our model is

In [59]:
#Create a list of models
model_list = []
X_test_list = []
y_test_list = []
#[rfc_film_video, rfc_publishing, rfc_design, rfc_art, rfc_food, rfc_fashion, rfc_games, rfc_theater, rfc_music, rfc_crafts, rfc_technology, rfc_comics]
#Train each model
i = 0
for df in kc_dfs:
    #Set X (independent vars) and y(dependent vars)
    X = df.drop(["mainCategory", "success"], axis=1)
    y = df['success']
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)
    #Store test data into the lists so that we can use them outside of the function
    #Each X_test_list element is a dataframe
    X_test_list.append(X_test)
    y_test_list.append(y_test)
    rfc = RandomForestClassifier(n_estimators=200)
    rfc.fit(X_train,y_train)
    model_list.append(rfc)

In [60]:
#Test each model
i = 0
for model in model_list:
    X_test_data = X_test_list[i]
    y_test_data = y_test_list[i]
    pred = model.predict(X_test_data)
    print(classification_report(y_test_data,pred))
    print(confusion_matrix(y_test_data,pred))
    i += 1

             precision    recall  f1-score   support

          0       1.00      0.92      0.96        74
          1       0.90      1.00      0.95        53

avg / total       0.96      0.95      0.95       127

[[68  6]
 [ 0 53]]
             precision    recall  f1-score   support

          0       1.00      0.98      0.99        81
          1       0.96      1.00      0.98        45

avg / total       0.98      0.98      0.98       126

[[79  2]
 [ 0 45]]
             precision    recall  f1-score   support

          0       1.00      0.92      0.96        62
          1       0.90      1.00      0.95        43

avg / total       0.96      0.95      0.95       105

[[57  5]
 [ 0 43]]
             precision    recall  f1-score   support

          0       1.00      0.98      0.99        51
          1       0.97      1.00      0.98        30

avg / total       0.99      0.99      0.99        81

[[50  1]
 [ 0 30]]
             precision    recall  f1-score   support

          

In [62]:
#model list: [rfc_film_video, rfc_publishing, rfc_design, rfc_art, rfc_food, rfc_fashion, rfc_games, rfc_theater, rfc_music, rfc_crafts, rfc_technology, rfc_comics]
model_list[0]
print(X_test_list[1].iloc[0])

category                     8.000000
goal                      2500.000000
duration                    59.958333
numPerks                     6.000000
medianPerk                  40.000000
estimatedDelivery           53.050694
mainVideo                    0.000000
numSuccessfulCampaigns       0.000000
facebookFriends            716.000000
numCollaborators             0.000000
totWordCount               373.000000
numImages                    0.000000
Name: 619, dtype: float64


In [64]:
print((X_test_list[1].iloc[0]))

category                     8.000000
goal                      2500.000000
duration                    59.958333
numPerks                     6.000000
medianPerk                  40.000000
estimatedDelivery           53.050694
mainVideo                    0.000000
numSuccessfulCampaigns       0.000000
facebookFriends            716.000000
numCollaborators             0.000000
totWordCount               373.000000
numImages                    0.000000
Name: 619, dtype: float64


In [71]:
test_value = X_test_list[1].iloc[0]
pred = games_model.predict(test_value)
print(pred)

[0]


C:\Program Files\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [54]:
print(type(games_model))

<class 'sklearn.ensemble.forest.RandomForestClassifier'>


In [ ]:
games_model.predict()